#!/usr/bin/env bash
#
# This is a simple script that will plot a TSV file as a line graph using
# gnuplot.  You can run it like so, passing the name of the input TSV file
# as the first argument and the name of the output JPEG file as the second
# argument:
#
#   ./generate_plot_from_tsv input.tsv output.jpg
#

#
# Show usage information if arguments aren't present.
#
if [ "$#" -lt 2 ]; then
    echo "Usage: ${0} input.tsv output.jpg"
    exit 1;
fi



gnuplot -e "set terminal jpeg;set output '${2}'; set style data lines;plot '${1}';"